// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzpQD4lW2KEbrsTbCrmlSEqjqa7iLgHOs',
    appId: '1:200131044276:web:a5e0eb88e2a67188d748e1',
    messagingSenderId: '200131044276',
    projectId: 'flutter-1-24-demo1',
    authDomain: 'flutter-1-24-demo1.firebaseapp.com',
    storageBucket: 'flutter-1-24-demo1.appspot.com',
    measurementId: 'G-06MHCCNWJ9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAAt2KPWGy0E3GQL0Rn5cSkr45KIkWNpc',
    appId: '1:200131044276:android:65839b234853ed8fd748e1',
    messagingSenderId: '200131044276',
    projectId: 'flutter-1-24-demo1',
    storageBucket: 'flutter-1-24-demo1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxSu2v8tRGKxa5G_hQa0PEhv39Iq6ATis',
    appId: '1:200131044276:ios:079e0448bf00dcdad748e1',
    messagingSenderId: '200131044276',
    projectId: 'flutter-1-24-demo1',
    storageBucket: 'flutter-1-24-demo1.appspot.com',
    iosBundleId: 'com.example.firebaseDemo1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxSu2v8tRGKxa5G_hQa0PEhv39Iq6ATis',
    appId: '1:200131044276:ios:079e0448bf00dcdad748e1',
    messagingSenderId: '200131044276',
    projectId: 'flutter-1-24-demo1',
    storageBucket: 'flutter-1-24-demo1.appspot.com',
    iosBundleId: 'com.example.firebaseDemo1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDzpQD4lW2KEbrsTbCrmlSEqjqa7iLgHOs',
    appId: '1:200131044276:web:643c97a9280b02b7d748e1',
    messagingSenderId: '200131044276',
    projectId: 'flutter-1-24-demo1',
    authDomain: 'flutter-1-24-demo1.firebaseapp.com',
    storageBucket: 'flutter-1-24-demo1.appspot.com',
    measurementId: 'G-JB8CJZ9JS8',
  );
}
