// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRdQn1R6gJmYYO89udgOdI-2-g5Uh6BPQ',
    appId: '1:631772242777:android:807e12bf361b7f3f0de248',
    messagingSenderId: '631772242777',
    projectId: 'scapp-firestore',
    storageBucket: 'scapp-firestore.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBojtp8jZU93fE1JqgELH_3M1gkSD3J3Iw',
    appId: '1:631772242777:ios:fd5531a79d7a73ea0de248',
    messagingSenderId: '631772242777',
    projectId: 'scapp-firestore',
    storageBucket: 'scapp-firestore.appspot.com',
    iosBundleId: 'com.example.scappFirestore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBojtp8jZU93fE1JqgELH_3M1gkSD3J3Iw',
    appId: '1:631772242777:ios:fd5531a79d7a73ea0de248',
    messagingSenderId: '631772242777',
    projectId: 'scapp-firestore',
    storageBucket: 'scapp-firestore.appspot.com',
    iosBundleId: 'com.example.scappFirestore',
  );
}
